# Generated by Django 4.0.4 on 2022-05-15 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_django', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('-updated',), 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterModelTable(
            name='task',
            table='task_task_list_model_table',
        ),
    ]
